// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonkeyButler.Data.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MonkeyButler.Migrations
{
    [DbContext(typeof(MonkeyButlerContext))]
    [Migration("20200625180129_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MonkeyButler.Data.Models.Database.FreeCompanyOptions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FreeCompanyOptions");
                });

            modelBuilder.Entity("MonkeyButler.Data.Models.Database.GuildOptions", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("FreeCompanyId")
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<string>("Server")
                        .HasColumnType("text");

                    b.Property<List<string>>("SignupEmotes")
                        .HasColumnType("text[]");

                    b.Property<string>("VerifiedRole")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FreeCompanyId");

                    b.ToTable("GuildOptions");
                });

            modelBuilder.Entity("MonkeyButler.Data.Models.Database.GuildOptions", b =>
                {
                    b.HasOne("MonkeyButler.Data.Models.Database.FreeCompanyOptions", "FreeCompany")
                        .WithMany()
                        .HasForeignKey("FreeCompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
